[package]
name = "serial-console"
version = "1.0.0"
edition = "2021"

[dependencies]
serialport = "4.0.1"
anyhow = "1"
structopt = "0.3.25"

[profile.release]
codegen-units = 1
lto = true
# opt-level = "z"